<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>io</string>
	</array>
	<key>name</key>
	<string>Io</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b(clone|method|return)\b</string>
			<key>name</key>
			<string>keyword.io</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(do|if|then|elseif|else|while|loop|repeat|for|ifTrue|ifFalse|foreach|map)\b</string>
			<key>name</key>
			<string>keyword.control.io</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"""</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.io</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"""</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.io</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.tripple.quoted.io</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.io</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.io</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.double.quoted.io</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\[abnrtv\"]</string>
					<key>name</key>
					<string>constant.character.escape.io</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>\b((0[xX][0-9a-fA-F]+)|[0-9]+|(([0-9]\.[0-9]+)|(\.[0-9]+))([eE](\+|-)?[0-9]+)?)\b</string>
			<key>name</key>
			<string>constant.numeric.io</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(nil|true|false)\b</string>
			<key>name</key>
			<string>constant.language.io</string>
		</dict>
		<dict>
			<key>match</key>
			<string>//.*$</string>
			<key>name</key>
			<string>comment.cpp.io</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\#.*$</string>
			<key>name</key>
			<string>comment.sh.io</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.c.io</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.io</string>
	<key>uuid</key>
	<string>ffc44989-eb67-43c1-af9b-b6547a75e83c</string>
</dict>
</plist>
